[default]

# DEFININDO O TAMANHO DO KERNEL GAUSSIANO PARA DESFOQUE
BLUR_KSIZE = 5

# DEFININDO O VALOR DE PIXEL QUE SERÁ USADO COMO LIMIAR
THRESHOLD_MAX_COLOR_VALUE = 255

# DEFININDO O TAMANHO DO KERNEL GAUSSIANO PARA DILATAÇÃO
DILATION_KSIZE = 5

# TAMANHO DE SAÍDA DA IMAGEM (QUADRADA)
OUTPUT_SIZE = 600

[development]