[default]

# DEFININDO O TAMANHO DO KERNEL GAUSSIANO PARA DESFOQUE
BLUR_KSIZE = 5

# DEFININDO O VALOR DE PIXEL QUE SERÁ USADO COMO LIMIAR
THRESHOLD_MAX_COLOR_VALUE = 255

# DEFININDO O TAMANHO DO KERNEL GAUSSIANO PARA DILATAÇÃO
DILATION_KSIZE = 5

# LARGURA PARA RESIZE DA IMAGEM
WIDTH_RESIZE = 600

# TAMANHO DE SAÍDA DA IMAGEM (QUADRADA)
OUTPUT_SIZE = 600

# TAMANHO DO KERNEL PARA THRESHOLD
THRESHOLD_KSIZE = 11

# VARIÁVEL QUE REPRESENTA A CONSTANTE UTILIZADA NOS MÉTODOS (SUBTRAÍDA DA MÉDIA OU MÉDIA PONDERADA)
SUBTRACT_FROM_MEAN = 1

[development]