[default]

# NOME DO MODELO
APPNAME = 'OCR_RG'

# DIRETÓRIO DE SAVE DOS LOGS
DIR_SAVE_LOGS = 'LOGS'

# ARQUIVO DE SAVE DOS LOGS - LOGGING
LOG_FILENAME = 'LOG_OCR_RG.log'

# LEVEL DE CRITICIDADE DO LOG A SER REGISTRADO
LOGLEVEL = 'DEBUG'
LOGLEVEL_FILE = 'DEBUG'
LOGLEVEL_CONSOLE = 'INFO'

# INICIANDO A VARIÁVEL DE LOGGERS
LOGGERS = {}

# ARQUIVO DE SAVE DOS LOGS - BANCO DE DADOS - SQLIE
DB_LOGS = 'LOG_OCR_RG.db'

# DEFININDO O TAMANHO DO KERNEL GAUSSIANO PARA DESFOQUE
BLUR_KSIZE = 5

# DEFININDO O VALOR DE PIXEL QUE SERÁ USADO COMO LIMIAR
THRESHOLD_MAX_COLOR_VALUE = 255

# DEFININDO O TAMANHO DO KERNEL GAUSSIANO PARA DILATAÇÃO
DILATION_KSIZE = 5

# LARGURA PARA RESIZE DA IMAGEM
WIDTH_RESIZE = 600

# TAMANHO DE SAÍDA DA IMAGEM (QUADRADA)
OUTPUT_SIZE = 600

# TAMANHO DO KERNEL PARA THRESHOLD
THRESHOLD_KSIZE = 11

# VARIÁVEL QUE REPRESENTA A CONSTANTE UTILIZADA NOS MÉTODOS (SUBTRAÍDA DA MÉDIA OU MÉDIA PONDERADA)
SUBTRACT_FROM_MEAN = 1

[development]