[default]

# NOME DO MODELO
APPNAME = 'OCR_RG'

# DIRETÓRIO DE SAVE DOS LOGS
DIR_SAVE_LOGS = 'LOGS'

# ARQUIVO DE SAVE DOS LOGS - LOGGING
LOG_FILENAME = 'LOG_OCR_RG.log'

# LEVEL DE CRITICIDADE DO LOG A SER REGISTRADO
LOGLEVEL = 'DEBUG'
LOGLEVEL_FILE = 'DEBUG'
LOGLEVEL_CONSOLE = 'INFO'

# INICIANDO A VARIÁVEL DE LOGGERS
LOGGERS = {}

# ARQUIVO DE SAVE DOS LOGS - BANCO DE DADOS - SQLITE
DB_LOGS = 'LOG_OCR_RG.db'

# DEFININDO CAMPOS ACEITOS PELO MODELO
FIELDS = ["RG", "DATA_EXPED", "NOME", "NOME_MAE", "NOME_PAI", "DATA_NASC", "CPF", "CIDADE_NASC", "ESTADO_NASC", "CIDADE_ORIGEM", "ESTADO_ORIGEM"]

# DEFININDO O TAMANHO DO KERNEL GAUSSIANO PARA DESFOQUE
BLUR_KSIZE = 5

# DEFININDO O VALOR DE PIXEL QUE SERÁ USADO COMO LIMIAR
THRESHOLD_MAX_COLOR_VALUE = 255

# DEFININDO O TAMANHO DO KERNEL GAUSSIANO PARA DILATAÇÃO
DILATION_KSIZE = 5

# LARGURA PARA RESIZE DA IMAGEM
WIDTH_RESIZE = 600

# TAMANHO DE SAÍDA DA IMAGEM (QUADRADA)
OUTPUT_SIZE = 600

# TAMANHO DO KERNEL PARA THRESHOLD
THRESHOLD_KSIZE = 11

# VARIÁVEL QUE REPRESENTA A CONSTANTE UTILIZADA NOS MÉTODOS (SUBTRAÍDA DA MÉDIA OU MÉDIA PONDERADA)
SUBTRACT_FROM_MEAN = 1

# PARÂMETROS DO OCR - TESSERACT
TESSERACT_LANG = 'eng'
TESSERACT_PSM = '1'
TESSERACT_OEM = '3'

# PARÂMETRO DO TIPO DE RETORNO DO OCR
TIPO_OCR = "TEXTO"

# SELECIONA APENAS LETRAS
REGEX_ONLY_LETTERS = '[^A-zÀ-ù]'

# SELECIONA APENAS NÚMEROS
REGEX_ONLY_NUMBERS = '[^\d]'

# SELECIONA APENAS LETRAS E NÚMEROS
REGEX_ONLY_LETTERS_NUMBERS = '[^A-Za-z0-9]+'

# SELECIONA APENAS LETRAS, PONTOS, BARRAS, TRAÇOS E NÚMEROS
REGEX_ONLY_LETTERS_NUMBERS_DOT_BARS_DASHES = '[^A-Za-z0-9\-.\/]'

# SELECIONA APENAS A LETRA X, PONTOS, BARRAS, TRAÇOS E NÚMEROS
REGEX_ONLY_X_NUMBERS_DOT_BARS_DASHES = '[^xX0-9\-.\/]'

# SELECIONA APENAS A LETRA X E NÚMEROS
REGEX_ONLY_X_NUMBERS = '[^xX0-9]'

# SELECIONA APENAS DATAS
REGEX_ONLY_DATES = '([0-9]{1,2}(\/|-))?([A-Za-z]{1,3}|[0-9]{1,3})(\/|-)[0-9]{2,4}'

# SELECIONA APENAS LETRAS, PONTO (.) E TRAÇO (-)
REGEX_ONLY_LETTERS_DOT_DASH = '[^(A-zÀ-ù)(\-)(.)]'

# INICIANDO OS PERCENTUAIS DE MATCH DEFAULT
DEFAULT_PERCENTUAL_MATCH = 70

# DEFININDO SE DEVE HAVER PRÉ PROCESSAMENTO DOS ITENS ANTES DO CÁLCULO DE SEMELHANÇA
DEFAULT_PRE_PROCESSING = false

# INICIANDO A VARIÁVEL QUE CONTÉM O LIMIT NA CHAMADA DE MÁXIMAS SIMILARIDADES
DEFAULT_LIMIT_RESULT_BEST_SIMILAR = 1

# DIRETÓRIO DA BASE DE NOMES E GENEROS
dir_data_first_names_gender = '..\BD_OCR_RG\DATASET_NOMES_GENERO.csv'

# DIRETÓRIO DA BASE DE SOBRENOMES
dir_data_last_names = '..\BD_OCR_RG\DATASET_LAST_NAMES.csv'

    [default.fields]
    # DEFININDO AS COORDENADAS PARA CORTE DOS CAMPOS
    # ARRAYS DEVEM POSSUIR TIPAGEM HOMOGENEA NO TOML SYNTAX
    # A CONVERSÃO DE STRING PARA INT OCORRE NO FLUXO DO CÓDIGO
    RG = ['RG', '1']
    DATA_EXPED = ['DATA_EXPED', '1']
    NOME = ['NOME', '1']
    NOME_MAE = ['NOME_MAE', '1']
    NOME_PAI = ['NOME_PAI', '1']
    DATA_NASC = ['DATA_NASC', '1']
    CPF = ['CPF', '1']
    CIDADE_NASC = ['CIDADE_NASC', '1']
    ESTADO_NASC = ['ESTADO_NASC', '1']

    [default.coords]
    # DEFININDO AS COORDENADAS PARA CORTE DOS CAMPOS
    # ARRAYS DEVEM POSSUIR TIPAGEM HOMOGENEA NO TOML SYNTAX
    # A CONVERSÃO DE STRING PARA INT OCORRE NO FLUXO DO CÓDIGO
    RG = ['RG', 'GERAL', '1', '87', '35', '280', '96']
    DATA_EXPED = ['DATA_EXPED', 'GERAL', '1', '400', '35', '540', '110']
    NOME = ['NOME', 'GERAL', '1', '21', '80', '566', '173']
    NOME_MAE = ['NOME_MAE', 'GERAL', '1', '21', '240', '566', '300']
    NOME_PAI = ['NOME_PAI', 'GERAL', '1', '21', '206', '566', '234']
    DATA_NASC = ['DATA_NASC', 'GERAL', '1', '15', '310', '394', '380']
    CPF = ['CPF', 'GERAL', '1', '20', '450', '240', '520']
    CIDADE_NASC = ['CIDADE_NASC', 'GERAL', '1', '15', '310', '394', '380']
    ESTADO_NASC = ['ESTADO_NASC', 'GERAL', '1', '15', '310', '394', '380']

[development]

# LOCAL/NOME DO BANCO DE DADOS
DIR_BD_OCR = 'BD_OCR_RG/BD_OCR_RG.db'

# QUERY PARA OBTER OS CAMPOS ATIVOS E ACEITOS PELO MODELO
QUERY_FIELDS = 'SELECT FIELD, DOC_VERSO FROM TBL_FIELDS WHERE ATIVO = 1'
QUERY_TYPE_FIELDS = 'SELECT'

# QUERY PARA OBTER AS COORDENADAS DE CORTE DAS MASKS DE OCR
QUERY_COORD = 'SELECT TBL_FIELDS.FIELD, TBL_TEMPLATES.NOME_TEMPLATE, X1, Y1, X2, Y2, TBL_FIELDS.DOC_VERSO FROM TBL_COORDENADAS_MASK INNER JOIN TBL_FIELDS ON TBL_COORDENADAS_MASK.ID_FIELD = TBL_FIELDS.ID_FIELD INNER JOIN TBL_TEMPLATES ON TBL_TEMPLATES.ID_TEMPLATE = TBL_COORDENADAS_MASK.TEMPLATE WHERE TBL_FIELDS.ATIVO = 1;'
QUERY_TYPE_COORD = 'SELECT'

# QUERY PARA OBTER A BASE DO IBGE (MUNICIPIOS/ESTADOS)
QUERY_MUNICIPIOS_UF = 'SELECT MUNICIPIO, UF, ESTADO FROM TBL_ESTADOS_MUNICIPIOS'
QUERY_TYPE_MUNICIPIOS_UF = 'SELECT'

# QUERY PARA OBTER OS REGEX DISPONÍVEIS
QUERY_REGEX = 'SELECT NAME_REGEX, VALUE_REGEX FROM TBL_REGEX WHERE ATIVO = 1'
QUERY_TYPE_REGEX = 'SELECT'